import { c as create_ssr_component } from "../../../chunks/ssr.js";
const css = {
  code: '.svelte-1oaqgaq{background-image:npm_lifecycle_script(\r\n      "/static/loginAssets/DALL· A minimalist abstract background.webp"\r\n    )}',
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-1vi3xn4_START -->${$$result.title = `<title>Home</title>`, ""}<meta name="description" content="Visit Neretva" class="svelte-1oaqgaq"><!-- HEAD_svelte-1vi3xn4_END -->`, ""} <form class="w-full max-w-screen-sm svelte-1oaqgaq" data-svelte-h="svelte-1wzh5ss"><div class="md:flex md:items-center mb-6 svelte-1oaqgaq"><div class="md:w-1/3 svelte-1oaqgaq"><label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4 svelte-1oaqgaq" for="inline-full-name">Username</label></div> <div class="md:w-2/3 svelte-1oaqgaq"><input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 svelte-1oaqgaq" id="inline-full-name" type="text" placeholder="Enter your username"></div></div> <div class="md:flex md:items-center mb-6 svelte-1oaqgaq"><div class="md:w-1/3 svelte-1oaqgaq"><label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4 svelte-1oaqgaq" for="inline-password">Password</label></div> <div class="md:w-2/3 svelte-1oaqgaq"><input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 svelte-1oaqgaq" id="inline-password" type="password" placeholder="**********"></div></div> <div class="md:flex md:items-center mb-6 svelte-1oaqgaq"><div class="md:w-1/3 svelte-1oaqgaq"></div> <label class="md:w-2/3 block text-gray-500 font-bold svelte-1oaqgaq"><input class="mr-2 leading-tight svelte-1oaqgaq" type="checkbox"> <span class="text-sm svelte-1oaqgaq">I would like to receive your newsletter!</span></label></div> <div class="md:flex md:items-center svelte-1oaqgaq"><div class="md:w-1/3 svelte-1oaqgaq"></div> <div class="md:w-2/3 gap-5 svelte-1oaqgaq"><button class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded svelte-1oaqgaq" type="button">Sign Up</button> <button class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded svelte-1oaqgaq" type="button">Sign In</button></div></div> </form>`;
});
export {
  Page as default
};
