export const spots = [
  {
    name: "Biking for family",
    type: "Bike Trail",
    description: "Bike Trail for hard core",
    longDescription: "Bike Trail for hard core. Explore rivers and coastlines with guided kayak tours. Perfect for families looking to challenge themselves with exciting trails while enjoying the great outdoors.",
    averageRating: 4.5,
    pic: "Spots_bike_trail.JPG",
    id: 0,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Surf school",
    type: "Activity",
    description: "Place to learn and enjoy surfing.",
    longDescription: "A premier destination for aspiring surfers of all ages. Learn the basics or hone your skills with experienced instructors in a fun and supportive environment.",
    averageRating: 4.7,
    pic: "surf school.jpg",
    id: 1,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Rock Climbing Camp",
    type: "Activity",
    description: "Challenging vertical climbs for all skill levels.",
    longDescription: "Engage in the ultimate rock climbing adventure. Our camp offers routes for beginners to advanced climbers, focusing on safety, technique, and fun.",
    averageRating: 4.8,
    pic: "rock climbing school.jpg",
    id: 2,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Kayak Adventures",
    type: "Activity",
    description: "Explore rivers and coastlines with guided kayak tours.",
    longDescription: "Discover the beauty of nature through our guided kayak tours. Explore serene rivers, rugged coastlines, and get up close with local wildlife in their natural habitat.",
    averageRating: 4.6,
    pic: "kayak adventures.jpg",
    id: 3,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Hiking Trails Expedition",
    type: "Activity",
    description: "Discover breathtaking trails and scenic views.",
    longDescription: "Join our hiking trails expedition to uncover the wonders of nature. From beginner-friendly paths to challenging treks, experience scenic vistas and unparalleled natural beauty.",
    averageRating: 4.9,
    pic: "trails expedition.jpg",
    id: 4,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Mountain Biking Blast",
    type: "Activity",
    description: "Experience thrilling downhill and cross-country trails.",
    longDescription: "For adrenaline seekers, our mountain biking blast offers the ultimate experience. Tackle downhill slopes and rugged cross-country trails with expert guides.",
    averageRating: 4.4,
    pic: "Mountain Biking Blast.jpg",
    id: 5,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Skydiving Thrill",
    type: "Activity",
    description: "Skydive with experienced instructors for an adrenaline rush.",
    longDescription: "Take the leap and experience the thrill of skydiving. Our certified instructors will guide you through every step, ensuring a safe and exhilarating jump.",
    averageRating: 4.9,
    pic: "Skydiving Thrill.jpg",
    id: 6,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Sailing School",
    type: "Activity",
    description: "Learn to sail in the open sea with certified instructors.",
    longDescription: "Embark on a sailing adventure with our certified sailing school. Learn navigation, boat handling, and safety on the open sea, guided by experienced sailors.",
    averageRating: 4.3,
    pic: "Sailing School.jpg",
    id: 7,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Wildlife Safari",
    type: "Activity",
    description: "Get up close with nature and wildlife in their natural habitat.",
    longDescription: "Experience the thrill of a wildlife safari. Venture into the wilderness with our guides to see animals in their natural habitat, learn about conservation, and enjoy the beauty of nature.",
    averageRating: 4.7,
    pic: "Wildlife Safari.webp",
    id: 8,
    price: "$110.00",
    address: "123 Example St, City4, Country",
    website: "www.newSite4.com",
    phoneNumber: "+321-654-98704",
  },
  {
    name: "Scuba Diving Discovery",
    type: "Activity",
    description: "Explore underwater worlds and marine life.",
    longDescription: "Dive into the ocean's depths with our scuba diving discovery program. Explore coral reefs, encounter marine life, and uncover the mysteries of the underwater world.",
    averageRating: 4.8,
    pic: "Scuba Diving Discovery.jpg",
    id: 9,
    price: "$95.00",
    address: "123 Example St, City3, Country",
    website: "www.newSite3.com",
    phoneNumber: "+321-654-98703",
  },
  {
    name: "Snowboarding Camp",
    type: "Activity",
    description: "Hit the slopes with professional coaching and fun snowboarding sessions.",
    longDescription: "Our snowboarding camp is designed for enthusiasts of all levels. From beginner to advanced, improve your skills with professional coaching on some of the best slopes.",
    averageRating: 4.6,
    pic: "Snowboarding Camp.webp",
    id: 10,
    price: "$80.00",
    address: "123 Example St, City2, Country",
    website: "www.newSite2.com",
    phoneNumber: "+321-654-98702",
  },
  {
    name: "Yoga Retreat",
    type: "Activity",
    description: "Relax and rejuvenate with yoga sessions in serene locations.",
    longDescription: "Our yoga retreat offers a sanctuary for relaxation and rejuvenation. Engage in yoga sessions in serene locations, guided by expert instructors, and find your inner peace.",
    averageRating: 4.9,
    pic: "Yoga Retreat.jpg",
    id: 11,
    price: "$65.00",
    address: "123 Example St, City1, Country",
    website: "www.newSite1.com",
    phoneNumber: "+321-654-98701",
  },
];


export const reviews = [
  {
    id: 1,
    user: "User1",
    rating: 5,
    comment: "Absolutely loved it! Highly recommend."
  },
  {
    id: 2,
    user: "User2",
    rating: 4,
    comment: "Great experience, but room for improvement."
  },
  {
    id: 3,
    user: "User3",
    rating: 3,
    comment: "Average experience, was expecting more."
  },
  {
    id: 4,
    user: "User4",
    rating: 2,
    comment: "Below expectations in several areas."
  },
  {
    id: 5,
    user: "User5",
    rating: 1,
    comment: "Disappointing service, would not recommend."
  }
];
