export const spots = [
  {
    name: "Biking for family",
    type: "Bike Trail",
    description: "Bike Trail for hard core",
    averageRating: 4.5,
    pic: "Spots_bike_trail.JPG",
    id: 0,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Surf school",
    type: "Activity",
    description: "Place to learn and enjoy surfing.",
    averageRating: 4.7,
    pic: "surf school.jpg",
    id: 1,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Rock Climbing Camp",
    type: "Activity",
    description: "Challenging vertical climbs for all skill levels.",
    averageRating: 4.8,
    pic: "rock climbing school.jpg",
    id: 2,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Kayak Adventures",
    type: "Activity",
    description: "Explore rivers and coastlines with guided kayak tours.",
    averageRating: 4.6,
    pic: "kayak adventures.jpg",
    id: 3,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Hiking Trails Expedition",
    type: "Activity",
    description: "Discover breathtaking trails and scenic views.",
    averageRating: 4.9,
    pic: "trails expedition.jpg",
    id: 4,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },

  {
    name: "Mountain Biking Blast",
    type: "Activity",
    description: "Experience thrilling downhill and cross-country trails.",
    averageRating: 4.4,
    pic: "Mountain Biking Blast.jpg",
    id: 5,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Skydiving Thrill",
    type: "Activity",
    description: "Skydive with experienced instructors for an adrenaline rush.",
    averageRating: 4.9,
    pic: "Skydiving Thrill.jpg",
    id: 6,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Sailing School",
    type: "Activity",
    description: "Learn to sail in the open sea with certified instructors.",
    averageRating: 4.3,
    pic: "Sailing School.jpg",
    id: 7,
    price: "Placeholder for price",
    address: "Placeholder for address",
    website: "Placeholder for website",
    phoneNumber: "Placeholder for phone number",
  },
  {
    name: "Wildlife Safari",
    type: "Activity",
    description:
      "Get up close with nature and wildlife in their natural habitat.",
    averageRating: 4.7,
    pic: "Wildlife Safari.webp",
    id: 8,
    website: "www.newSite4.com",
    phoneNumber: "+321-654-98704",
    price: "$110.00",
    address: "123 Example St, City4, Country",
  },
  {
    name: "Scuba Diving Discovery",
    type: "Activity",
    description: "Explore underwater worlds and marine life.",
    averageRating: 4.8,
    pic: "Scuba Diving Discovery.jpg",
    id: 9,
    website: "www.newSite3.com",
    phoneNumber: "+321-654-98703",
    price: "$95.00",
    address: "123 Example St, City3, Country",
  },
  {
    name: "Snowboarding Camp",
    type: "Activity",
    description:
      "Hit the slopes with professional coaching and fun snowboarding sessions.",
    averageRating: 4.6,
    pic: "Snowboarding Camp.webp",
    id: 10,
    website: "www.newSite2.com",
    phoneNumber: "+321-654-98702",
    price: "$80.00",
    address: "123 Example St, City2, Country",
  },
  {
    name: "Yoga Retreat",
    type: "Activity",
    description: "Relax and rejuvenate with yoga sessions in serene locations.",
    averageRating: 4.9,
    pic: "Yoga Retreat.jpg",
    id: 11,
    website: "www.newSite1.com",
    phoneNumber: "+321-654-98701",
    price: "$65.00",
    address: "123 Example St, City1, Country",
  },
];

export const reviews = [
  {
    id: 1,
    user: "User1",
    rating: 5,
    comment: "Absolutely loved it! Highly recommend."
  },
  {
    id: 2,
    user: "User2",
    rating: 4,
    comment: "Great experience, but room for improvement."
  },
  {
    id: 3,
    user: "User3",
    rating: 3,
    comment: "Average experience, was expecting more."
  },
  {
    id: 4,
    user: "User4",
    rating: 2,
    comment: "Below expectations in several areas."
  },
  {
    id: 5,
    user: "User5",
    rating: 1,
    comment: "Disappointing service, would not recommend."
  }
];
